function Nm = Nm_2412(xi,eta)
%Nm_2412
%    Nm = Nm_2412(XI,ETA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    20-Jan-2025 21:47:13

t2 = eta./4.0;
t3 = xi./4.0;
t7 = eta.*xi.*(-1.0./4.0);
t4 = t2.*xi;
t5 = -t2;
t6 = -t3;
t8 = t2+t3+t4+1.0./4.0;
t9 = t4+t5+t6+1.0./4.0;
t10 = t3+t5+t7+1.0./4.0;
t11 = t2+t6+t7+1.0./4.0;
Nm = reshape([t9,0.0,0.0,t9,t10,0.0,0.0,t10,t8,0.0,0.0,t8,t11,0.0,0.0,t11],[2,8]);
end
