function Nm_eta = Nm_2412_eta(xi,eta)
%Nm_2412_eta
%    Nm_eta = Nm_2412_eta(XI,ETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    03-Mar-2025 19:09:02

t2 = xi./4.0;
t3 = -t2;
t4 = t2+1.0./4.0;
t6 = t2-1.0./4.0;
t5 = t3+1.0./4.0;
t7 = t3-1.0./4.0;
Nm_eta = reshape([t6,0.0,0.0,t6,t7,0.0,0.0,t7,t4,0.0,0.0,t4,t5,0.0,0.0,t5],[2,8]);
end
